### ISSUE TITLE
Missing IP address and netmask options in the "Create an NVMe/FC LIF" section

### ISSUE THREAD

**Issue by gbaschkier** [NetAppDocs/ontap#1415]
### Page URL

https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-nvme-task.html

### Page title

Configure a storage VM for NVMe

### Summary

Hi. I found that the IP address and netmask options are missing in the "Create an NVMe/FC LIF" section. The CLI output shows me a message stating that. 
Both for the ONTAP versions 9.10.1 and later, and 9.9 and earlier in the document.
Regards,

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-barbe** [comment]
Thank you for the feedback, this will be updated shortly

**Comment by netapp-barbe** [comment]
This issue has been fixed. Thank you for your feedback!

**Comment by gbaschkier** [comment]
Hi All,
The "netmask" option is wrong. It should say

*-netmask <netmask value>*

Instead of :

-address <ip address> *-netmask <ip address>* (this is incorrect, the
document still shows this)

Regards,

**Comment by netapp-barbe** [comment]
Thank you - correction made
